### ISSUE TITLE
test/ken/divconst.go fails for sparc64 SSA backend

### ISSUE THREAD

**Issue by binarycrusader** [4ad/go#36]
# go run run.go -- ken/divconst.go
exit status 1
u8 214 0 128 1
panic: fail

goroutine 1 [running]:
panic(0xc9f00, 0xc42000c160)
        /builds/srwalker/golang/go-sparc/src/runtime/panic.go:507 +0x5fc
main.u8test(0xd60080014000f5b2)
        /builds/srwalker/golang/go-sparc/test/ken/divconst.go:576 +0x1e8
main.u8run()
        /builds/srwalker/golang/go-sparc/test/ken/divconst.go:615 +0x2f4
main.main()
        /builds/srwalker/golang/go-sparc/test/ken/divconst.go:630 +0x74
exit status 2

FAIL    ken/divconst.go 1.167s

**Comment by binarycrusader** [comment]
This is likely related to #31.

**Comment by binarycrusader** [comment]
Actually, completely unrelated to #31.  This was a simple oversight in failing to properly sign-extend or zero-extend values smaller than 64-bit, as all divisions on sparc64 are performed using SDIVX/UDIVX, which are 64-bit.

Fixed.
