### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by toomasp** [4ad/go#37]
1. What version of Go are you using (`go version`)?

```bash
toomasp@tar1312d1:/opt/local/tmp/go/src$ GOROOT=$GOROOT_BOOTSTRAP $GOROOT_BOOTSTRAP/bin/go version
go version devel +69a12818b6 Mon Dec 19 10:29:52 2016 -0800 solaris/sparc64
```

2. What operating system and processor architecture are you using (`go env`)?

```bash
toomasp@tar1312d1:/opt/local/tmp/go/src$ GOROOT=$GOROOT_BOOTSTRAP $GOROOT_BOOTSTRAP/bin/go env    
GOARCH="sparc64"
GOBIN=""
GOEXE=""
GOHOSTARCH="sparc64"
GOHOSTOS="solaris"
GOOS="solaris"
GOPATH=""
GORACE=""
GOROOT="/opt/local/tmp/go_bootstrapper"
GOTOOLDIR="/opt/local/tmp/go_bootstrapper/pkg/tool/solaris_sparc64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build228464990=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

toomasp@tar1312d1:/opt/local/tmp/go/src$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/gcc/5/lib/gcc/sparcv9-sun-solaris2.11/5.4.0/lto-wrapper
Target: sparcv9-sun-solaris2.11
Configured with: /builds/ul11u3sru-gate/components/gcc5/gcc-5.4.0/configure CC='/usr/gcc/4.7/bin/gcc -m64' CXX='/usr/gcc/4.7/bin/g++ -m64' --prefix=/usr/gcc/5 --mandir=/usr/gcc/5/share/man --bindir=/usr/gcc/5/bin --libdir=/usr/gcc/5/lib --sbindir=/usr/gcc/5/sbin --infodir=/usr/gcc/5/share/info --libexecdir=/usr/gcc/5/lib --enable-languages=c,c++,fortran,objc --enable-shared --enable-initfini-array --disable-rpath --with-system-zlib --with-build-config=no --with-gmp-include=/usr/include/gmp --with-mpfr-include=/usr/include/mpfr --without-gnu-ld --with-ld=/usr/bin/ld --with-gnu-as --with-as=/usr/gnu/bin/as 'BOOT_CFLAGS=-g -O2' sparcv9-sun-solaris2.11
Thread model: posix
gcc version 5.4.0 (GCC) 
```

3. What did you do?

```bash
toomasp@tar1312d1:/opt/local/tmp/go/src$ ./all.bash 
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /opt/local/tmp/go_bootstrapper.
bootstrap/internal/sys
bootstrap/asm/internal/flags
bootstrap/internal/bio
bootstrap/compile/internal/big
bootstrap/internal/gcprog
bootstrap/internal/obj
bootstrap/internal/obj/arm
bootstrap/internal/obj/s390x
bootstrap/internal/obj/sparc64
bootstrap/internal/obj/arm64
bootstrap/internal/obj/ppc64
bootstrap/internal/obj/mips
bootstrap/internal/obj/x86
bootstrap/asm/internal/lex
bootstrap/link/internal/ld
bootstrap/compile/internal/ssa
bootstrap/asm/internal/arch
bootstrap/asm/internal/asm
bootstrap/asm
bootstrap/link/internal/amd64
bootstrap/link/internal/arm
bootstrap/link/internal/arm64
bootstrap/link/internal/mips64
bootstrap/link/internal/ppc64
bootstrap/link/internal/s390x
bootstrap/link/internal/sparc64
bootstrap/link/internal/x86
bootstrap/link
bootstrap/compile/internal/gc
bootstrap/compile/internal/arm
bootstrap/compile/internal/amd64
bootstrap/compile/internal/ppc64
bootstrap/compile/internal/mips64
bootstrap/compile/internal/s390x
bootstrap/compile/internal/arm64
bootstrap/compile/internal/sparc64
bootstrap/compile/internal/x86
bootstrap/compile

##### Building go_bootstrap for host, solaris/sparc64.
runtime/internal/sys
runtime/internal/atomic
runtime
math
unicode/utf8
sort
sync/atomic
encoding
unicode
unicode/utf16
errors
internal/syscall/windows/sysdll
internal/race
sync
container/heap
internal/singleflight
syscall
io
hash
hash/adler32
strings
bytes
strconv
bufio
path
internal/syscall/windows/registry
internal/syscall/windows
time
encoding/base64
reflect
regexp/syntax
crypto
crypto/sha1
os
regexp
path/filepath
os/signal
io/ioutil
encoding/binary
fmt
log
text/template/parse
debug/dwarf
net/url
go/token
compress/flate
context
encoding/json
flag
go/scanner
os/exec
go/ast
text/template
compress/zlib
debug/macho
debug/elf
go/parser
go/doc
go/build
cmd/go

##### Building packages and commands for solaris/sparc64.
runtime/internal/sys
runtime/internal/atomic
runtime
errors
internal/race
math
sync/atomic
sort
unicode
unicode/utf8
container/list
container/ring
crypto/subtle
internal/nettrace
encoding
unicode/utf16
image/color
internal/syscall/windows/sysdll
runtime/race
cmd/compile/internal/test
cmd/vet/internal/whitelist
sync
syscall
io
internal/singleflight
container/heap
image/color/palette
crypto/cipher
hash
runtime/trace
strings
bytes
hash/crc32
crypto/hmac
hash/adler32
hash/crc64
hash/fnv
math/cmplx
math/rand
strconv
bufio
text/tabwriter
html
vendor/golang_org/x/net/lex/httplex
path
time
compress/bzip2
crypto
crypto/aes
regexp/syntax
reflect
crypto/rc4
encoding/base64
encoding/ascii85
encoding/base32
image
crypto/sha512
crypto/md5
crypto/sha1
crypto/sha256
encoding/pem
os
image/internal/imageutil
image/draw
image/jpeg
regexp
path/filepath
os/signal
runtime/debug
io/ioutil
cmd/internal/pprof/svg
fmt
encoding/binary
crypto/des
index/suffixarray
cmd/internal/sys
log
flag
compress/flate
archive/tar
debug/plan9obj
debug/gosym
cmd/vendor/golang.org/x/arch/arm/armasm
cmd/vendor/golang.org/x/arch/x86/x86asm
debug/dwarf
compress/lzw
context
math/big
encoding/hex
go/token
database/sql/driver
encoding/csv
encoding/gob
encoding/json
encoding/xml
mime
vendor/golang_org/x/net/http2/hpack
mime/quotedprintable
net/http/internal
net/url
text/scanner
text/template/parse
runtime/pprof
net/internal/socktest
cmd/compile/internal/big
cmd/internal/gcprog
cmd/internal/pprof/tempfile
image/gif
testing/iotest
cmd/pack
cmd/internal/bio
database/sql
go/scanner
os/exec
testing/quick
cmd/asm/internal/flags
cmd/internal/obj
testing
go/ast
internal/trace
text/template
compress/zlib
archive/zip
compress/gzip
internal/testenv
debug/macho
debug/pe
debug/elf
image/png
cmd/dist
cmd/internal/pprof/profile
cmd/internal/obj/arm64
cmd/internal/obj/mips
cmd/internal/obj/arm
cmd/internal/goobj
cmd/internal/obj/ppc64
cmd/internal/obj/s390x
cmd/internal/obj/sparc64
cmd/internal/obj/x86
cmd/asm/internal/lex
go/printer
go/parser
crypto/dsa
crypto/elliptic
encoding/asn1
crypto/rand
go/constant
cmd/link/internal/ld
cmd/internal/objfile
go/doc
html/template
crypto/rsa
cmd/addr2line
cmd/nm
cmd/objdump
cmd/internal/pprof/plugin
cmd/internal/pprof/symbolz
cmd/internal/pprof/symbolizer
crypto/ecdsa
crypto/x509/pkix
cmd/compile/internal/ssa
go/types
cmd/cgo
go/format
cmd/gofmt
go/build
cmd/fix
cmd/yacc
cmd/vet/internal/cfg
cmd/internal/pprof/report
cmd/cover
cmd/doc
cmd/asm/internal/arch
cmd/internal/pprof/commands
cmd/asm/internal/asm
cmd/internal/pprof/driver
cmd/asm
runtime/cgo
net
os/user
go/internal/gcimporter
go/internal/gccgoimporter
cmd/api
cmd/link/internal/amd64
cmd/link/internal/arm64
cmd/link/internal/ppc64
cmd/link/internal/arm
cmd/link/internal/mips64
cmd/link/internal/s390x
cmd/link/internal/sparc64
cmd/link/internal/x86
go/importer
cmd/vet
cmd/link
crypto/x509
net/http/httptrace
net/textproto
log/syslog
mime/multipart
net/mail
crypto/tls
cmd/compile/internal/gc
net/http
net/smtp
expvar
net/http/cgi
net/http/httptest
net/http/cookiejar
net/http/httputil
net/http/pprof
net/rpc
cmd/go
cmd/internal/pprof/fetch
cmd/trace
cmd/pprof
net/http/fcgi
net/rpc/jsonrpc
cmd/compile/internal/arm
cmd/compile/internal/amd64
cmd/compile/internal/arm64
cmd/compile/internal/ppc64
cmd/compile/internal/mips64
cmd/compile/internal/s390x
cmd/compile/internal/sparc64
cmd/compile/internal/x86
cmd/compile


##### Testing packages.
ok      archive/tar     0.298s
ok      archive/zip     1.598s
ok      bufio   1.172s
ok      bytes   1.853s
ok      compress/bzip2  2.994s
ok      compress/flate  14.237s
ok      compress/gzip   1.440s
ok      compress/lzw    0.948s
ok      compress/zlib   0.903s
ok      container/heap  1.111s
ok      container/list  1.339s
ok      container/ring  1.087s
ok      context 2.192s
ok      crypto/aes      1.137s
ok      crypto/cipher   0.695s
ok      crypto/des      1.340s
ok      crypto/dsa      1.345s
ok      crypto/ecdsa    3.228s
ok      crypto/elliptic 1.138s
ok      crypto/hmac     1.042s
ok      crypto/md5      0.848s
ok      crypto/rand     1.411s
ok      crypto/rc4      2.415s
ok      crypto/rsa      5.771s
ok      crypto/sha1     0.934s
ok      crypto/sha256   1.018s
ok      crypto/sha512   0.982s
ok      crypto/subtle   1.051s
ok      crypto/tls      13.382s
ok      crypto/x509     7.754s
ok      database/sql    0.345s
ok      database/sql/driver     0.853s
ok      debug/dwarf     1.324s
ok      debug/elf       0.327s
ok      debug/gosym     1.186s
ok      debug/macho     1.300s
ok      debug/pe        1.406s
ok      debug/plan9obj  2.009s
ok      encoding/ascii85        1.077s
ok      encoding/asn1   0.103s
ok      encoding/base32 1.300s
ok      encoding/base64 1.147s
ok      encoding/binary 0.242s
ok      encoding/csv    1.303s
ok      encoding/gob    0.222s
ok      encoding/hex    1.205s
ok      encoding/json   1.723s
ok      encoding/pem    1.417s
ok      encoding/xml    0.077s
ok      errors  1.063s
ok      expvar  0.595s
ok      flag    1.102s
ok      fmt     0.413s
ok      go/ast  0.084s
ok      go/build        1.152s
ok      go/constant     0.492s
ok      go/doc  0.481s
ok      go/format       0.723s
ok      go/internal/gccgoimporter       0.559s
ok      go/internal/gcimporter  3.278s
ok      go/parser       0.388s
ok      go/printer      3.945s
ok      go/scanner      1.184s
ok      go/token        1.622s
ok      go/types        3.028s
ok      hash/adler32    1.186s
ok      hash/crc32      0.445s
ok      hash/crc64      0.369s
ok      hash/fnv        1.081s
ok      html    1.074s
ok      html/template   0.270s
ok      image   1.390s
ok      image/color     2.750s
ok      image/draw      1.239s
ok      image/gif       1.425s
ok      image/jpeg      2.472s
ok      image/png       0.737s
ok      index/suffixarray       1.463s
ok      internal/singleflight   1.200s
ok      internal/trace  1.313s
ok      io      0.477s
ok      io/ioutil       1.228s
ok      log     1.315s
ok      log/syslog      3.495s
ok      math    0.104s
ok      math/big        3.367s
ok      math/cmplx      1.441s
ok      math/rand       1.990s
ok      mime    0.214s
ok      mime/multipart  7.321s
ok      mime/quotedprintable    7.718s
ok      net     1.625s
ok      net/http        22.825s
ok      net/http/cgi    1.271s
ok      net/http/cookiejar      0.127s
ok      net/http/fcgi   0.187s
ok      net/http/httptest       0.148s
ok      net/http/httptrace      1.360s
ok      net/http/httputil       0.361s
ok      net/http/internal       1.274s
ld.so.1: socktest.test: fatal: relocation error: file /tmp/go-build268274901/net/internal/socktest/_test/socktest.test: symbol socket: referenced symbol not found
FAIL    net/internal/socktest   0.980s
ok      net/mail        0.113s
ok      net/rpc 0.207s
ok      net/rpc/jsonrpc 0.144s
ok      net/smtp        0.438s
ok      net/textproto   0.204s
ok      net/url 0.114s
ok      os      1.352s
ok      os/exec 2.978s
ok      os/signal       5.653s
ok      os/user 0.065s
ok      path    1.248s
ok      path/filepath   0.292s
ok      reflect 0.579s
ok      regexp  2.466s
ok      regexp/syntax   4.648s
--- FAIL: TestCgoTracebackContext (0.02s)
        crash_test.go:105: testprogcgo TracebackContext exit status: exit status 2
        crash_cgo_test.go:233: expected "OK\n" got SIGABRT: used by abort, replace SIGIOT in the future
                PC=0xffffffff7f04e7e0 m=0
                signal arrived during cgo execution
                
                goroutine 1 [syscall, locked to thread]:
                runtime.cgocall(0x100235a44, 0xc4200f1c10, 0x200f1b68)
                        /opt/local/tmp/go/src/runtime/cgocall.go:131 +0x248 fp=0xc4200f1a90 sp=0xc4200f19b0
                main._Cfunc_C1()
                        _/opt/local/tmp/go/src/runtime/testdata/testprogcgo/_obj/_cgo_gotypes.go:83 +0x64 fp=0xc4200f1b60 sp=0xc4200f1a90
                main.TracebackContext()
                        /opt/local/tmp/go/src/runtime/testdata/testprogcgo/tracebackctxt.go:37 +0xe8 fp=0xc4200f1cb0 sp=0xc4200f1b60
                main.main()
                        /opt/local/tmp/go/src/runtime/testdata/testprogcgo/main.go:34 +0x3cc fp=0xc4200f1de0 sp=0xc4200f1cb0
                runtime.main()
                        /opt/local/tmp/go/src/runtime/proc.go:183 +0x540 fp=0xc4200f1ee0 sp=0xc4200f1de0
                runtime.goexit()
                        /opt/local/tmp/go/src/runtime/asm_sparc64.s:1101 +0x4 fp=0xc4200f1ee0 sp=0xc4200f1ee0
                
                goroutine 17 [syscall, locked to thread]:
                runtime.goexit()
                        /opt/local/tmp/go/src/runtime/asm_sparc64.s:1101 +0x4
                
                goroutine 5 [runnable]:
                os/signal.loop()
                        /opt/local/tmp/go/src/os/signal/signal_unix.go:20
                created by os/signal.init.1
                        /opt/local/tmp/go/src/os/signal/signal_unix.go:28 +0x6c
                
                r1      0xa3
                r2      0x1
                r3      0x100364648
                r4      0x2
                r5      0x3ffffc00
                r6      0x0
                r7      0xffffffff7ee02a40
                r8      0x0
                r9      0x1
                r10     0x6
                r11     0x0
                r12     0xffffffffffffffff
                r13     0x0
                r16     0xffffffff7ee02a40
                r17     0x0
                r18     0x20
                r19     0x0
                r20     0x1
                r21     0x5
                r22     0x0
                r23     0x0
                r24     0x6
                r25     0x6
                r26     0x5
                r27     0x0
                r28     0x6
                r29     0x5
                r31     0xffffffff7efcbbac
                lr      0xffffffff7eff7be4
                sp      0xffffffff7fffe580
                fp      0xffffffff7fffe630
                pc      0xffffffff7f04e7e0
                npc     0xffffffff7f04e7e4
                fault   0xc000000000
FAIL
FAIL    runtime 40.570s
ok      runtime/debug   0.798s
ok      runtime/internal/atomic 2.092s
ok      runtime/internal/sys    0.370s
ok      runtime/pprof   14.230s
ok      runtime/trace   53.190s
ok      sort    0.872s
ok      strconv 3.771s
ok      strings 1.074s
ok      sync    1.577s
ok      sync/atomic     1.256s
ok      syscall 0.164s
ok      testing 2.197s
ok      testing/quick   0.684s
ok      text/scanner    0.118s
ok      text/tabwriter  0.112s
ok      text/template   4.940s
ok      text/template/parse     0.104s
--- FAIL: TestParseInLocation (0.02s)
        format_test.go:263: ParseInLocation(Feb 01 2013 AST, Baghdad) = 2013-02-01 00:00:00 +0000 AST, want 2013-02-01 00:00:00 +0300 +03
FAIL
FAIL    time    3.257s
ok      unicode 0.102s
ok      unicode/utf16   0.070s
ok      unicode/utf8    0.133s
ok      vendor/golang_org/x/net/http2/hpack     0.134s
ok      vendor/golang_org/x/net/lex/httplex     0.133s
ok      cmd/addr2line   5.846s
ok      cmd/api 0.076s
ok      cmd/asm/internal/asm    2.354s
ok      cmd/asm/internal/lex    0.081s
ok      cmd/compile/internal/big        2.992s
ok      cmd/compile/internal/gc 107.330s
ok      cmd/compile/internal/ssa        1.539s
ok      cmd/compile/internal/test       0.098s
ok      cmd/cover       8.987s
ok      cmd/doc 0.307s
ok      cmd/fix 0.109s
ok      cmd/go  117.115s
ok      cmd/gofmt       0.393s
ok      cmd/internal/goobj      0.055s
ok      cmd/internal/obj        0.052s
ok      cmd/internal/obj/x86    0.068s
ok      cmd/internal/pprof/profile      0.049s
ok      cmd/link        0.054s
ok      cmd/nm  4.861s
ok      cmd/objdump     0.062s
ok      cmd/pack        9.109s
ok      cmd/vendor/golang.org/x/arch/arm/armasm 0.066s
ok      cmd/vendor/golang.org/x/arch/x86/x86asm 1.079s
ok      cmd/vet 11.949s
ok      cmd/vet/internal/cfg    0.079s
2018/02/15 08:00:35 Failed: exit status 1
```

**Comment by ehrt74** [comment]
TestParseInLocation is easy enough to fix. see: https://go-review.googlesource.com/c/go/+/66073/2/src/time/format_test.go

and the discussion here: https://github.com/golang/go/issues/19457
