### ISSUE TITLE
go tool compile -R causes panic

### ISSUE THREAD

**Issue by 4ad** [4ad/go#6]
```
cd /tmp/a && GOOS=solaris GOARCH=sparc64 go tool compile -R conv.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xf0 pc=0xc47d1]

goroutine 1 [running]:
panic(0x573680, 0xc82000e230)
    /Users/aram/go/src/runtime/panic.go:483 +0x189
cmd/internal/obj.Dconv(0x0, 0xc820124e28, 0x4, 0x0)
    /Users/aram/go/src/cmd/internal/obj/util.go:416 +0xbe1
cmd/internal/obj.(*Link).Dconv(0xc820124000, 0xc820124e28, 0xc8204c1f10, 0x9)
    /Users/aram/go/src/cmd/internal/obj/util.go:366 +0x2a
cmd/compile/internal/gc.mkvar(0xc8200996b8, 0xc820124e28, 0x0, 0x0, 0x0)
    /Users/aram/go/src/cmd/compile/internal/gc/reg.go:490 +0x8f9
cmd/compile/internal/gc.regopt(0xc820124280)
    /Users/aram/go/src/cmd/compile/internal/gc/reg.go:1121 +0x2b13
cmd/compile/internal/gc.compile(0xc8200aa900)
    /Users/aram/go/src/cmd/compile/internal/gc/pgen.go:531 +0x863
cmd/compile/internal/gc.funccompile(0xc8200aa900)
    /Users/aram/go/src/cmd/compile/internal/gc/dcl.go:1437 +0x196
cmd/compile/internal/gc.Main()
    /Users/aram/go/src/cmd/compile/internal/gc/lex.go:488 +0x19f2
cmd/compile/internal/sparc64.Main()
    /Users/aram/go/src/cmd/compile/internal/sparc64/galign.go:80 +0x49c
main.main()
    /Users/aram/go/src/cmd/compile/main.go:43 +0x4bf
```

**Comment by 4ad** [comment]
This is not sparc64-specific, arm64 and ppc64 are the same, so this is not important until we need the debug output from -R.

**Comment by 4ad** [comment]
Fixed upstream.
